apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-rcsmezpj
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-rcsmezpj:7005b3b927408bd9913d02d80bdb8a20aa3a83a0@sha256:f1bcd4d1fdef9aeaa15d2a5c3a7e18d52e2fdfe018648bf3cd5a354270af1d48
        name: container-image  
